# Site Settings
baseurl: ""
url : "https://jennieablog.github.io"

# Blog Settings
theme_settings :
  title : Jennie Ablog
  favicon : assets/favicon.ico

  # Profile Settings
  profile :
    image : assets/img/profile.jpg
    logo : assets/logo.png
    qrcode: assets/img/qrcode.png
    username : Jennie Ablog
    description: BSc Computer Science student from UP Diliman 🇵🇭
    blog_description : I code and make puns.
    experience :
      - start : "June 2017 "
        end: "August 2017"
        experience : Intern, Nokia Manila TC
      - start : "July 2018"
        end: "August 2018"
        experience : Intern, UP ITDC
      - start : "2014"
        end : ""
        experience : BSc CS Student, UP Diliman
        
    programming : 
      - skill : python
      - skill : c
      - skill : c++
      - skill : java
      - skill : ruby

    webdev : 
      - skill : ruby on rails
      - skill : html5
      - skill : css3
      - skill : javascript
      - skill : jekyll
      - skill : react native
      - skill : flask
      - skill : bootstrap
    
    others : 
      - skill : git
      - skill : nem blockchain
      - skill : godot game engine
      - skill : blender
      - skill : sklearn
      - skill : pygame


  # Icons
  icons :
    email:  jsablog@up.edu.ph
    linkedin: https://www.linkedin.com/in/jennie-ron-ablog-489845143/
    github: jennieablog
    gitlab: 
    bitbucket: 
    google_plus:
    twitter: 
    youtube:
    facebook: 
    instagram:

  # Disqus
  disqus_shortname : jennieablog-github-io

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true
