# Site Settings
baseurl: ""
url : "https://jennieablog.github.io"

# Blog Settings
theme_settings :
  title : Jennie Ron Ablog
  favicon : assets/disk.ico

  # Profile Settings
  profile :
    image : assets/img/profile.jpg
    logo : assets/logo.png
    qrcode: assets/img/qrcode.png
    username : Jennie Ron Ablog
    description: BS Computer Science student from UP Diliman 🇵🇭
    blog_description : BS CS student from UP Diliman, writes code and likes puns.
    experience :
      - start : "June 2017 "
        end: "August 2017"
        experience : Intern, Nokia Manila TC
      - start : "July 2018"
        end: "August 2018"
        experience : Intern, UP ITDC
      - start : "2014"
        end : ""
        experience : BS CS Student, UP Diliman
        
    programming : 
      - skill : python
      - skill : c
      - skill : c++
      - skill : ruby
      - skill : java

    webdev : 
      - skill : ruby on rails
      - skill : jekyll
      - skill : flask
      - skill : html5
      - skill : css3
      - skill : javascript
      - skill : bootstrap
    
    others : 
      - skill : git
      - skill : nem blockchain
      - skill : godot game engine
      - skill : sklearn
      - skill : pygame


  # Icons
  icons :
    email:  jsablog@up.edu.ph
    linkedin: 
    github: jennieablog
    gitlab: 
    bitbucket: 
    google_plus:
    twitter: jennieablog
    youtube:
    facebook: 
    instagram:

  # Disqus
  disqus_shortname : jennieablog-github-io

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate,jekyll-sitemap]
bootstrap:
  assets: true
